# Generated by Django 3.2.16 on 2023-09-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_region_number_account_route_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(blank=True, choices=[('RSR', 'Route Sales Representative'), ('Merch', 'Merchandiser'), ('RM', 'Regional Manager'), ('DM', 'Division Manager'), ('WHM', 'Warehouse Manager')], default='', max_length=30),
        ),
    ]
