# Generated by Django 4.1.6 on 2023-02-21 12:37

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsr', '0003_alter_store_name'),
        ('operations', '0002_alter_item_item_size'),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('store', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='rsr.store')),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('startBool', models.BooleanField(default=True)),
                ('completeDate', models.DateTimeField(blank=True, null=True)),
                ('completeBool', models.BooleanField(default=False)),
                ('upload', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='/image')),
                ('OOS', models.ManyToManyField(blank=True, null=True, related_name='OOS', to='operations.item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='rsr.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('worked_cases', models.ManyToManyField(to='operations.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('startBool', models.BooleanField(default=True)),
                ('completeDate', models.DateTimeField(blank=True, null=True)),
                ('completeBool', models.BooleanField(default=False)),
                ('store_list', models.ManyToManyField(related_name='docket_store', to='rsr.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
