# Generated by Django 4.1.1 on 2023-01-01 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_brand', models.CharField(choices=[('P', 'Peets'), ('I', 'Intelligentsia'), ('S', 'Stumptown')], default='P', max_length=25)),
                ('item_type', models.CharField(choices=[('G', 'Ground'), ('W', 'Whole Bean'), ('K', 'K-Cup')], max_length=25)),
                ('item_size', models.CharField(choices=[('18', '18oz'), ('10.5', '10.5oz'), ('10.5', '10.5oz'), ('10', 'K-10'), ('22', 'K-22'), ('32', 'K-32'), ('48', 'K-48')], max_length=25)),
                ('item_name', models.CharField(max_length=100)),
                ('item_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='OOS_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='merch',
            name='case_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='merch',
            name='upload',
            field=models.ImageField(default='N/A', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(choices=[('Safeway', 'Safeway'), ('Lucky', 'Lucky'), ('Nob Hill', 'Nob Hill'), ('Wholefoods', 'Wholefoods')], max_length=25),
        ),
        migrations.CreateModel(
            name='WeeklyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('TotalStores', models.IntegerField(max_length=100)),
                ('TotalCases', models.IntegerField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merch.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='merch.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='merch',
            name='OOS',
            field=models.ManyToManyField(to='merch.item'),
        ),
    ]
