# Generated by Django 4.1.1 on 2022-11-11 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merch',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
