# Generated by Django 4.1.6 on 2023-02-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_item_item_size'),
        ('merch', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='worked_cases',
            field=models.ManyToManyField(blank=True, null=True, to='operations.orderitem'),
        ),
    ]
