# Generated by Django 4.1.1 on 2023-01-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_item_merch_oos_count_merch_case_count_merch_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Address',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='Area',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AddField(
            model_name='store',
            name='BS_Location',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='City',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AddField(
            model_name='store',
            name='Service_days',
            field=models.CharField(default='N/A', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(choices=[('Safeway', 'Safeway'), ('Lucky', 'Lucky'), ('Nob Hill', 'Nob Hill'), ('Wholefoods', 'Wholefoods')], default='Safeway', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.IntegerField(default='N/A', max_length=100),
        ),
    ]
