# Generated by Django 4.1.1 on 2023-01-20 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rsr', '0001_initial'),
        ('operations', '0001_initial'),
        ('merch', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ImageField(blank=True, default='N/A', null=True, upload_to='images')),
                ('OOS', models.ManyToManyField(blank=True, null=True, related_name='OOS', to='operations.item')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='rsr.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('worked_cases', models.ManyToManyField(blank=True, null=True, related_name='worked_cases', to='operations.item')),
            ],
        ),
    ]
