# Generated by Django 4.1.1 on 2023-01-20 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merch', '0003_merch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('store_list', models.ManyToManyField(related_name='docket_store', to='rsr.store')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docket_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
