# Generated by Django 4.1.1 on 2022-11-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='OOS',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
