# Generated by Django 4.1.1 on 2023-01-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_store_address_store_area_store_bs_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='OOS_count',
        ),
    ]
