# Generated by Django 4.1.6 on 2023-02-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0003_alter_merch_worked_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='docket',
            name='merch_list',
            field=models.ManyToManyField(related_name='docket_merch', to='merch.merch'),
        ),
        migrations.AddField(
            model_name='docket',
            name='planDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
