# Generated by Django 4.1.6 on 2023-03-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0004_storelistitem'),
        ('merch', '0004_docket_merch_list_docket_plandate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docket',
            name='store_list',
            field=models.ManyToManyField(related_name='docket_store', to='rsr.storelistitem'),
        ),
    ]
