# Generated by Django 4.1.1 on 2022-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_merch_oos'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='case_count',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
