# Generated by Django 4.1.1 on 2023-01-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0004_remove_merch_oos_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='OOS',
            field=models.ManyToManyField(blank=True, to='merch.item'),
        ),
    ]
