# Generated by Django 4.1.1 on 2023-01-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_alter_merch_oos'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='RSRrt',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.IntegerField(blank=True, default='N/A', max_length=100),
        ),
    ]
