# Generated by Django 4.1.6 on 2023-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0005_alter_docket_store_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
