# Generated by Django 4.1.6 on 2023-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_merch_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
