# Generated by Django 4.1.1 on 2022-11-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_alter_merch_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(max_length=100)),
            ],
        ),
    ]
