# Generated by Django 4.1.1 on 2023-01-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0006_store_rsrrt_alter_store_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydata',
            name='merch',
            field=models.ManyToManyField(blank=True, to='merch.merch'),
        ),
        migrations.AlterField(
            model_name='store',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='Area',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='BS_Location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='City',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='RSRrt',
            field=models.IntegerField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='Service_days',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(choices=[('Safeway', 'Safeway'), ('Target', 'Target'), ('Lucky', 'Lucky'), ('FoodMaxx', 'FoodMaxx'), ('SaveMart', 'SaveMart'), ('Lunardis', 'Lunardis'), ('Nob Hill', 'Nob Hill'), ('Wholefoods', 'Wholefoods'), ('BerkeleyBowl', 'BerkeleyBowl')], default='Safeway', max_length=25),
        ),
        migrations.AlterField(
            model_name='store',
            name='number',
            field=models.IntegerField(blank=True, default='', max_length=100, null=True),
        ),
    ]
