# Generated by Django 4.1.1 on 2023-01-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_weeklydata_merch_alter_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydata',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
