# Generated by Django 4.1.1 on 2022-11-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0007_weeklydata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeeklyData',
        ),
    ]
