# Generated by Django 4.1.1 on 2023-01-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0008_weeklydata_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklydata',
            name='merch',
        ),
        migrations.AddField(
            model_name='merch',
            name='Week',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='merch.weeklydata'),
        ),
    ]
