# Generated by Django 4.1.1 on 2022-11-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0008_delete_weeklydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='merch',
            name='upload',
            field=models.ImageField(default='N/A', upload_to=''),
        ),
    ]
