# Generated by Django 4.1.1 on 2023-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0009_remove_weeklydata_merch_merch_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='case_count',
        ),
        migrations.RemoveField(
            model_name='store',
            name='Service_days',
        ),
        migrations.AddField(
            model_name='merch',
            name='worked_cases',
            field=models.ManyToManyField(blank=True, related_name='worked_cases', to='merch.item'),
        ),
        migrations.AddField(
            model_name='store',
            name='receiver_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='store',
            name='weekly_average',
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='merch',
            name='OOS',
            field=models.ManyToManyField(blank=True, related_name='OOS', to='merch.item'),
        ),
    ]
