# Generated by Django 4.1.1 on 2022-11-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0009_merch_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='upload',
            field=models.ImageField(default='N/A', upload_to='images/'),
        ),
    ]
