# Generated by Django 4.1.1 on 2023-01-10 19:07

from django.db import migrations, models
import merch.models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0010_remove_merch_case_count_remove_store_service_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='receiver_open',
            field=models.TimeField(default=merch.models.default_start_time),
        ),
    ]
