# Generated by Django 4.1.1 on 2023-01-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0012_store_receiver_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='receive_type',
            field=models.CharField(choices=[('DEX', 'DEX'), ('SCAN', 'SCAN'), ('SIGN', 'SIGN')], default='DEX', max_length=25),
        ),
    ]
