# Generated by Django 4.1.1 on 2022-12-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0013_weeklydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merch',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='merch',
            name='upload',
            field=models.ImageField(default='N/A', upload_to='images'),
        ),
    ]
