# Generated by Django 4.1.1 on 2023-01-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merch', '0013_store_receive_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Displays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('BOH', 'Back of house'), ('FOH', 'Front of house'), ('Aisle', 'Aisle'), ('Bakery', 'Bakery'), ('Deli', 'Deli'), ('Pharmacy', 'Pharmacy'), ('Check-stand', 'Check-stand')], default='End cap', max_length=25)),
                ('type', models.CharField(choices=[('Shipper', 'Shipper'), ('Wire rack', 'Wire rack'), ('Hanging rack', 'Hanging rack'), ('End cap', 'End cap'), ('Rolling rack', 'Rolling rack')], default='Shipper', max_length=25)),
                ('description', models.CharField(default='', max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
