# Generated by Django 4.1.1 on 2023-01-10 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merch', '0014_displays'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Displays',
            new_name='Display',
        ),
        migrations.AddField(
            model_name='store',
            name='displays',
            field=models.ManyToManyField(to='merch.display'),
        ),
    ]
