# Generated by Django 4.1.1 on 2023-01-14 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0015_rename_displays_display_store_displays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merch',
            name='Week',
        ),
        migrations.AlterField(
            model_name='merch',
            name='OOS',
            field=models.ManyToManyField(blank=True, null=True, related_name='OOS', to='merch.item'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='store',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='merch.store'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='upload',
            field=models.ImageField(blank=True, default='N/A', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='merch',
            name='worked_cases',
            field=models.ManyToManyField(blank=True, null=True, related_name='worked_cases', to='merch.item'),
        ),
    ]
