# Generated by Django 4.1.1 on 2022-12-21 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0015_item_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
