# Generated by Django 4.1.1 on 2023-01-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0016_remove_merch_week_alter_merch_oos_alter_merch_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='displays',
            field=models.ManyToManyField(blank=True, null=True, related_name='Display', to='merch.display'),
        ),
    ]
