# Generated by Django 4.1.1 on 2022-12-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0019_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sport Wear'), ('OW', 'Out Wear')], max_length=2)),
                ('label', models.CharField(choices=[('N', 'New'), ('BS', 'Best Seller')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
