# Generated by Django 4.1.1 on 2022-12-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0021_order_orderitem_delete_cart_order_items_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
