# Generated by Django 4.1.1 on 2022-12-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0022_remove_item_category_remove_item_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_size',
            field=models.IntegerField(default=0),
        ),
    ]
