# Generated by Django 4.1.1 on 2022-12-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0023_item_item_number_item_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.IntegerField(default=0),
        ),
    ]
