# Generated by Django 4.1.1 on 2022-12-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0024_item_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.CharField(choices=[('10.5', '18'), ('10', '12')], max_length=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('PG', 'PW'), ('IG', 'IW'), ('SG', 'SW')], max_length=4),
        ),
    ]
