# Generated by Django 4.1.1 on 2022-12-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0025_remove_item_description_alter_item_item_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.CharField(choices=[('18oz', '18'), ('10.5oz', '10.5')], max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('G', 'Ground'), ('W', 'Whole Bean')], max_length=25),
        ),
    ]
