# Generated by Django 4.1.6 on 2023-02-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_size',
            field=models.CharField(choices=[('18', '18oz'), ('10.5', '10.5oz'), ('10', 'K-10'), ('22', 'K-22'), ('32', 'K-32'), ('48', 'K-48')], max_length=25),
        ),
    ]
