# Generated by Django 4.1.6 on 2023-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_item_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cpc',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
