# Generated by Django 3.2.16 on 2023-03-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_item_cpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
