# Generated by Django 3.2.16 on 2023-03-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20230327_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
