# Generated by Django 3.2.16 on 2023-04-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_inventoryitem_item_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='inventory',
            field=models.ManyToManyField(blank=True, null=True, to='operations.Inventory'),
        ),
    ]
