# Generated by Django 3.2.16 on 2023-07-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_rename_last_inventory_inventory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('name', models.TextField(default='N/A')),
                ('region', models.IntegerField(default=0)),
                ('order', models.ManyToManyField(blank=True, null=True, to='operations.Order')),
            ],
        ),
    ]
