# Generated by Django 3.2.16 on 2023-07-20 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Route',
        ),
    ]
