# Generated by Django 3.2.16 on 2023-07-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0004_storelistitem'),
        ('operations', '0010_delete_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='routes',
            field=models.ManyToManyField(blank=True, null=True, to='rsr.Route'),
        ),
    ]
