# Generated by Django 3.2.16 on 2023-07-20 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0004_storelistitem'),
        ('operations', '0011_warehouse_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='routes',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='routes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsr.route'),
        ),
    ]
