# Generated by Django 3.2.16 on 2023-07-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20230719_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
