# Generated by Django 3.2.16 on 2023-09-06 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0015_order_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='route',
        ),
    ]
