# Generated by Django 3.2.16 on 2023-09-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0004_storelistitem'),
        ('operations', '0016_remove_order_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='rsr.route'),
        ),
    ]
