# Generated by Django 3.2.16 on 2023-09-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0017_order_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('P', 'Preparing'), ('S', 'Shipped')], default='Pending', max_length=25),
        ),
    ]
