# Generated by Django 3.2.16 on 2023-09-07 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsr', '0004_storelistitem'),
        ('operations', '0018_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='route',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='rsr.route'),
        ),
    ]
