# Generated by Django 3.2.16 on 2024-01-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0019_alter_order_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='ship_date',
        ),
    ]
