# Generated by Django 3.2.16 on 2024-01-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0020_rename_ordered_date_order_ship_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Preparing', 'Preparing'), ('Shipping', 'Shipping')], default='Pending', max_length=25),
        ),
    ]
