# Generated by Django 3.2.16 on 2024-02-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0021_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OOSinventorylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.inventory')),
            ],
        ),
    ]
