# Generated by Django 3.2.16 on 2024-02-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0022_oos'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfStockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(help_text='The unique item number for the OOS item', max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OOS',
        ),
    ]
