# Generated by Django 4.1.1 on 2023-01-20 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rsr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('BOH', 'Back of house'), ('FOH', 'Front of house'), ('Aisle', 'Aisle'), ('Bakery', 'Bakery'), ('Deli', 'Deli'), ('Pharmacy', 'Pharmacy'), ('Check-stand', 'Check-stand')], default='End cap', max_length=25)),
                ('type', models.CharField(choices=[('Shipper', 'Shipper'), ('Wire rack', 'Wire rack'), ('Hanging rack', 'Hanging rack'), ('End cap', 'End cap'), ('Rolling rack', 'Rolling rack')], default='Shipper', max_length=25)),
                ('description', models.CharField(default='', max_length=140)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Safeway', 'Safeway'), ('Target', 'Target'), ('Lucky', 'Lucky'), ('FoodMaxx', 'FoodMaxx'), ('SaveMart', 'SaveMart'), ('Lunardis', 'Lunardis'), ('Nob Hill', 'Nob Hill'), ('Wholefoods', 'Wholefoods'), ('BerkeleyBowl', 'BerkeleyBowl')], default='Safeway', max_length=25)),
                ('number', models.IntegerField(blank=True, default='', max_length=100, null=True)),
                ('City', models.CharField(default='', max_length=25)),
                ('RSRrt', models.IntegerField(default='', max_length=100)),
                ('Area', models.CharField(default='', max_length=25)),
                ('receiver_name', models.CharField(default='', max_length=25)),
                ('receiver_open', models.TimeField(default=rsr.models.default_start_time)),
                ('receiver_close', models.TimeField(default=rsr.models.default_start_time)),
                ('receive_type', models.CharField(choices=[('DEX', 'DEX'), ('SCAN', 'SCAN'), ('SIGN', 'SIGN')], default='DEX', max_length=25)),
                ('weekly_average', models.IntegerField(default=0, max_length=100)),
                ('Address', models.CharField(default='', max_length=50)),
                ('BS_Location', models.CharField(default='', max_length=50)),
                ('displays', models.ManyToManyField(blank=True, null=True, related_name='Display', to='rsr.display')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Monday', max_length=25)),
                ('frequency', models.IntegerField(blank=True, default=0, max_length=100, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rsr.store')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default='0')),
                ('region', models.IntegerField(blank=True, default='4208')),
                ('store', models.ManyToManyField(blank=True, to='rsr.store')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
